-- 코드를 입력하세요
SELECT BOARD.TITLE
      ,BOARD.BOARD_ID
      ,REPLY.REPLY_ID
      ,REPLY.WRITER_ID
      ,REPLY.CONTENTS
      ,TO_CHAR(REPLY.CREATED_DATE, 'yyyy-mm-dd')
FROM USED_GOODS_BOARD BOARD 
JOIN USED_GOODS_REPLY REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID 
WHERE BOARD.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD')
                          AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC;